# render.yaml - Configuração para Render
services:
  - type: web
    name: email-classifier-api
    env: python
    buildCommand: "pip install -r requirements.txt && python -c 'import nltk; nltk.download(\"punkt\"); nltk.download(\"stopwords\")'"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Definir manualmente no painel do Render
      - key: ENVIRONMENT
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3