# render.yaml - Configuração para Render
services:
  - type: web
    name: email-classifier-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Definir manualmente no painel do Render
      - key: ENVIRONMENT
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3